### ISSUE TITLE
ESP32-A1S github examples

### ISSUE THREAD

**Issue by 06091971** [pschatzmann/ESP32-A2DP#551] opened 2024-05-04 22:04 UTC
### Problem Description

can you tell me how I may integrate this into home assistant or getting it working at all, a link with a video? I am very new to coding and want to learn, I will donate if I get some help, thanks, Jerry

### Device Description

esp32-a1s

### Sketch

```cpp
do not have one yet v2.2 a402
```

### Provide your Version of the EP32 Arduino Core (or the IDF Version)

v2.2 a402

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment] 2024-05-05 06:59
First of all, this is not a bug, and therefore not regarded as an issue. So I am closing this!

I don't think there is any programming needed: Just try to find out how to integrate a Bluetooth Speaker into Home Assistant

**Closed** 2024-05-05 06:59 UTC
